#!/usr/bin/env node

/**
 * 06-fetch/fetch.mjs
 *
 * Deterministic script for Step 6 (Fetch PR Comments).
 *
 * Usage:
 *   node 06-fetch/fetch.mjs <project-repo-location> <pr-number> <unanswered> <output-dir> <timestamp> <designated-branch> <pr-title>
 *
 * - <unanswered>: "true" or "false"
 *
 * Outputs JSON:
 * {
 *   "status": "OK" | "WARNING" | "ERROR",
 *   "message": "...",
 *   "commentCount": 0,
 *   "outputFile": "...",
 *   "errors": []
 * }
 *
 * Also writes the comments markdown file to <output-dir>/comments_<timestamp>.md
 */

import { writeFileSync, unlinkSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Strings to strip from comment bodies */
const STRIP_PATTERNS = [
  /Copilot is powered by AI,? so mistakes are possible\.?\s*Review output carefully before use\.?\s*/gi,
  /Copilot is powered by AI and may make mistakes\.?\s*Review output carefully before use\.?\s*/gi,
  /Generated by Copilot.*$/gim,
];

function cleanBody(body) {
  let cleaned = body;
  for (const pattern of STRIP_PATTERNS) {
    cleaned = cleaned.replace(pattern, "");
  }
  // Strip leading/trailing whitespace but preserve internal structure
  return cleaned.trim();
}

function friendlyAuthor(login) {
  if (!login) return "Unknown";
  const lower = login.toLowerCase();
  if (lower === "copilot-pull-request-reviewer[bot]" || lower === "copilot" || lower.startsWith("copilot"))
    return "Copilot";
  if (lower === "claude[bot]" || lower === "claude")
    return "Claude";
  return login;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = process.argv.slice(2);
  const repoDir = args[0] || ".";
  const prNumber = args[1] || "";
  const includeUnanswered = (args[2] || "false").toLowerCase() === "true";
  const outputDir = args[3] || ".";
  const timestamp = args[4] || "00000000-0000";
  const designatedBranch = args[5] || "";
  const prTitle = args[6] || "";

  const result = {
    status: "OK",
    message: "",
    commentCount: 0,
    outputFile: "",
    errors: [],
  };

  // -----------------------------------------------------------------------
  // Fetch review threads via GraphQL
  // -----------------------------------------------------------------------
  let threadsData;
  try {
    // Determine owner/repo from the gh CLI
    const repoInfo = execSync("gh repo view --json nameWithOwner -q .nameWithOwner", {
      encoding: "utf-8",
      cwd: repoDir,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();

    const [owner, repo] = repoInfo.split("/");

    const query = `
{
  repository(owner: "${owner}", name: "${repo}") {
    pullRequest(number: ${prNumber}) {
      reviewThreads(first: 100) {
        nodes {
          isResolved
          comments(first: 20) {
            nodes {
              author { login }
              body
              path
              startLine
              line
              diffHunk
              createdAt
            }
          }
        }
      }
    }
  }
}`;

    // Write query to a temp file to avoid shell quoting issues on Windows
    const tmpFile = join(outputDir, ".fetch-query-tmp.graphql");
    writeFileSync(tmpFile, query, "utf-8");

    let raw;
    try {
      raw = execSync(`gh api graphql -F query=@"${tmpFile}"`, {
        encoding: "utf-8",
        cwd: repoDir,
        stdio: ["pipe", "pipe", "pipe"],
        maxBuffer: 10 * 1024 * 1024,
      });
    } finally {
      // Clean up temp file
      try { unlinkSync(tmpFile); } catch { /* ignore */ }
    }

    threadsData = JSON.parse(raw);
  } catch (err) {
    result.status = "ERROR";
    result.errors.push(`Failed to fetch PR threads: ${err.message}`);
    result.message = result.errors.join(" ");
    process.stdout.write(JSON.stringify(result, null, 2));
    return;
  }

  const threads =
    threadsData?.data?.repository?.pullRequest?.reviewThreads?.nodes ?? [];

  if (threads.length === 0) {
    result.status = "WARNING";
    result.message = "No review threads found on this PR.";
    result.commentCount = 0;
    process.stdout.write(JSON.stringify(result, null, 2));
    return;
  }

  // -----------------------------------------------------------------------
  // Filter threads
  // -----------------------------------------------------------------------
  const qualifying = [];

  for (const thread of threads) {
    const comments = thread.comments?.nodes ?? [];
    if (comments.length === 0) continue;
    const firstComment = comments[0];

    if (!thread.isResolved) {
      // Unresolved — always include
      qualifying.push({ thread, firstComment, tag: null });
    } else if (includeUnanswered) {
      // Resolved — include only if unanswered (first comment has no replies)
      if (comments.length === 1) {
        qualifying.push({
          thread,
          firstComment,
          tag: "[resolved-unanswered]",
        });
      }
    }
  }

  if (qualifying.length === 0) {
    result.status = "OK";
    result.message = "No qualifying comments found (all threads are resolved).";
    result.commentCount = 0;
    process.stdout.write(JSON.stringify(result, null, 2));
    return;
  }

  // -----------------------------------------------------------------------
  // Build markdown
  // -----------------------------------------------------------------------
  const lines = [];
  lines.push(`# Comments — ${timestamp}`);
  lines.push("");
  lines.push(`PR #${prNumber}: "${prTitle}"`);
  lines.push(`Branch: ${designatedBranch}`);
  lines.push("");
  lines.push("---");

  let commentNum = 0;
  for (const { firstComment, tag } of qualifying) {
    commentNum++;
    const author = friendlyAuthor(firstComment.author?.login);
    const path = firstComment.path || "(no file)";
    const startLine = firstComment.startLine;
    const endLine = firstComment.line;
    const lineRange =
      startLine && endLine && startLine !== endLine
        ? `lines ${startLine}-${endLine}`
        : endLine
          ? `line ${endLine}`
          : "(no line)";
    const diffHunk = firstComment.diffHunk || "";
    const body = cleanBody(firstComment.body || "");

    lines.push("");
    lines.push(`## Comment ${commentNum}${tag ? " " + tag : ""}`);
    lines.push("");
    lines.push("### Author");
    lines.push("");
    lines.push(author);
    lines.push("");
    lines.push("### Location");
    lines.push("");
    lines.push(`\`${path}\`, ${lineRange}`);
    lines.push("");
    lines.push("### Diffs Snippet");
    lines.push("");
    lines.push("```");
    // Extract the last ~15 lines of the diff hunk for context
    const hunkLines = diffHunk.split("\n");
    const contextLines =
      hunkLines.length > 15 ? hunkLines.slice(-15) : hunkLines;
    lines.push(contextLines.join("\n"));
    lines.push("```");
    lines.push("");
    lines.push("### Comment Body");
    lines.push("");
    lines.push(body);
    lines.push("");
    lines.push("---");
  }

  // -----------------------------------------------------------------------
  // Write output file
  // -----------------------------------------------------------------------
  const outputFile = join(outputDir, `comments_${timestamp}.md`);
  try {
    writeFileSync(outputFile, lines.join("\n") + "\n", "utf-8");
  } catch (err) {
    result.status = "ERROR";
    result.errors.push(`Failed to write output file: ${err.message}`);
    result.message = result.errors.join(" ");
    process.stdout.write(JSON.stringify(result, null, 2));
    return;
  }

  result.commentCount = commentNum;
  result.outputFile = outputFile;
  result.message = `${commentNum} qualifying comment${commentNum !== 1 ? "s" : ""} found. Saved to comments_${timestamp}.md.`;

  process.stdout.write(JSON.stringify(result, null, 2));
}

main();
